# Generated by Django 4.2.3 on 2023-07-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('data_compra', models.CharField(blank=True, max_length=10, null=True)),
                ('data_validade', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('estoque_minimo', models.IntegerField(blank=True, null=True)),
                ('controle_estoque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produto/')),
                ('imgrediente', models.ManyToManyField(blank=True, to='produto.produto_model')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja_model')),
            ],
        ),
    ]
