# Generated by Django 4.2.3 on 2023-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_model',
            name='imgrediente',
            field=models.ManyToManyField(blank=True, related_name='ingre', to='produto.produto_model'),
        ),
    ]
