# Generated by Django 4.2.3 on 2023-07-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pix', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fiado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tipo', models.CharField(blank=True, max_length=7, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja_model')),
            ],
        ),
    ]
