# Generated by Django 4.2.3 on 2023-07-12 07:55

import cnpj_field.models
import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=300, null=True)),
                ('cpf', cpf_field.models.CPFField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True)),
                ('municipio', models.CharField(blank=True, max_length=300, null=True)),
                ('UF', models.CharField(blank=True, max_length=2, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loja_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=150, null=True)),
                ('cnpj', cnpj_field.models.CNPJField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('endereco', models.CharField(max_length=150, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('complemento', models.CharField(max_length=150, null=True)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('municipio', models.CharField(max_length=150, null=True)),
                ('UF', models.CharField(max_length=2, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='loja/')),
                ('ativo', models.BooleanField(default=True)),
                ('aberto', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('b', 'Bares'), ('l', 'Lanchonete'), ('r', 'Restaurante')], max_length=1)),
                ('tipo', models.CharField(default='comercio', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
