# Generated by Django 4.2.3 on 2023-07-12 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pix', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fiado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('frm_pg', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default='aberto', max_length=10, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja_model')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=300, null=True)),
                ('municipio', models.CharField(blank=True, max_length=300, null=True)),
                ('uf', models.CharField(blank=True, max_length=30, null=True)),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pix', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fiado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('frm_pg', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default='aberto', max_length=10, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja_model')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ped_mesa', to='pedido.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item_acrescimo', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ped', to='pedido.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prod', to='produto.produto_model')),
            ],
        ),
        migrations.CreateModel(
            name='Acrescimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arecimo', to='pedido.item')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produto.produto_model')),
            ],
        ),
    ]
