# Generated by Django 4.2.3 on 2023-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='venda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
