# Generated by Django 4.2.3 on 2023-07-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Und_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nota Fiscal')),
                ('dia', models.CharField(blank=True, max_length=10, null=True)),
                ('movimento', models.CharField(choices=[('e', 'entrada'), ('s', 'saida')], max_length=1)),
                ('total', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='aberto', max_length=10, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='loja.loja_model')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validade', models.CharField(max_length=30, null=True)),
                ('ncm', models.CharField(blank=True, max_length=50, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('preco_unid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja_model')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='estoque.nota_model')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto_model')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.und_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cep', models.CharField(max_length=30, null=True)),
                ('endereco', models.CharField(max_length=300, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=300, null=True)),
                ('municipio', models.CharField(max_length=300, null=True)),
                ('UF', models.CharField(max_length=30, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='loja.loja_model')),
            ],
        ),
    ]
